### ISSUE TITLE
Plugin - Resource Not Found

### ISSUE THREAD

**Issue by qupaloraarsuk** [facelessuser/RegReplace#102]
I have been able to implement a number of rules, and sequence them into one command, in order to normalize the spelling of some characters in a given text file (some characters were entered using two symbols, such as ᕐ+ᑭ, but should be replaced by a single one ᕿ, and so on). There are over about 60 rules to maintain. 

As per the documentation, and recommendations made to issues here, I tried to implement a plugin with a dictionary. 

When calling the plugin in the Command Palette, I get an error that the resource is not found. 

I copied the plugin "_norm_syll.py_" file into the "_RegReplace.sublime-package_" zip file. I also tried creating the "rr_modules" folder under /User/ and added the plugin there, but still got the same error message. 

I must admit that I'm new to Python. 

Hope you can help or direct me in the right direction.

- ST ver.: 3211
- Platform: linux
- Arch: x64
- Plugin ver.: 3.8.1
- Install via PC: True
- mdpopups ver.: 4.2.2
- backrefs ver.: 5.0
- regex ver.: 2.4.130
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

Traceback (most recent call last):
  File "/home/stephane/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages/RegReplace.sublime-package/rr_replacer.py", line 131, in on_replace
    module = Plugin.load(self.plugin)
  File "/home/stephane/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages/RegReplace.sublime-package/rr_plugin.py", line 72, in load
    module = cls.load_module(module_name, path_name)
  File "/home/stephane/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages/RegReplace.sublime-package/rr_plugin.py", line 51, in load_module
    sublime.load_resource(sublime_format_path(path_name)),
  File "/app/extra/sublime_text/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found

Rule
`"plugin_norm_syll":
{ "find": "([ᕐᑭ|ᕐᑮ|ᕐᑯ|ᕐᑰ|ᕐᑲ|ᕐᑳ|ᕐᒃ])",
"name": "plugin_norm_syll",
"plugin": "RegReplace.rr_modules.norm_syll" }`

Command 
`{ "caption": "Plugin: NormSyll",
"command": "reg_replace",
"args": {"replacements": ["plugin_norm_syll"]} }`

Plugin
`NAME_MAP = {
		"ᕐᑭ":	"ᕿ"
		"ᕐᑮ":	"ᖀ"
		"ᕐᑯ":	"ᖁ"
		"ᕐᑰ":	"ᖂ"
		"ᕐᑲ":	"ᖃ"
		"ᕐᑳ":	"ᖄ"
		"ᕐᒃ":	"ᖅ"
}

def replace(m):
    name = m.group(0)

    return NAME_MAP.get(name, name)`

**Comment by facelessuser** [comment]
Where did you physically put your plugin (path within the Sublime Text packages folder)? Is it in your `User` folder somewhere?

**Comment by qupaloraarsuk** [comment]
It is in the _User_ folder. The file is names _User.rr_modules.norm_syll.py_. 

Traceback (most recent call last):
  File "/home/stephane/.config/sublime-text/Installed Packages/RegReplace.sublime-package/rr_replacer.py", line 131, in on_replace
    module = Plugin.load(self.plugin)
  File "/home/stephane/.config/sublime-text/Installed Packages/RegReplace.sublime-package/rr_plugin.py", line 72, in load
    module = cls.load_module(module_name, path_name)
  File "/home/stephane/.config/sublime-text/Installed Packages/RegReplace.sublime-package/rr_plugin.py", line 51, in load_module
    sublime.load_resource(sublime_format_path(path_name)),
  File "/opt/sublime_text/Lib/python33/sublime.py", line 435, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages/User/rr_modules/norm_syll.py" not found

**Comment by facelessuser** [comment]
> The physical file is named User.rr_modules.norm_syll.py (I tried without .py but same error).

This statement confuses me a little. The file is literally named `User.rr_modules.norm_syll.py`? Or it is at the path `User/rr_modules/` and called `norm_syll.py`?

I would expect that you put it at `User/rr_modules/norm_syll.py` and reference it using Python module notation as `User.rr_modules.norm_syll`.

**Comment by qupaloraarsuk** [comment]
Now that works. 

I just need to debug my code in the plug-in. I believe i missed the comma after the first entry in my dictionary, and so on. 

I'll also work on the regex to simplify it in my rule.
