### ISSUE TITLE
Command not showing up in Command Palette (format 3.0 was given)

### ISSUE THREAD

**Issue by Jamahara** [facelessuser/RegReplace#82]
## Description

I can't seem to add commands to the command palette. Even though I add them to the User\Default.sublime-commands file, they aren't showing up when I try to access them via the command palette.

## Steps to Reproduce Issue

1. I first installed the extension via Package Control
2. Then, as stated in the user guide, I added my rules to the **User\reg_replace_rules.sublime-settings** file. Here is what the file looks like:

```
{
  "format": "3.0",
  "replacements": {
    "remove_deepl": {
      "find": "DeepL",
      "replace": "funzt",
      "greedy": true,
      "case": false
    },
  }
}
```

3. The next step was to add the following into my **User\Default.sublime-commands** file:
```

{
    "caption": "Reg Replace: Remove DeepL",
    "command": "reg_replace",
    "args": { "replacements": ["remove_deepl"] }
 },
```

As far as I understand, this should be enough to execute the regreplace via the command palette, but when I open it using the **CTRL+SHIFT+P** shortcut, and I type regreplace, the command isn't visible, as you can see in the screenshot.

![Image of Command Palette](https://i.imgur.com/QwlQQNE.png)

As this didn't work, I tried to use a key-binding and changed my **User\Default (Windows).sublime-keymap** to the following: 
```

{
	"keys": ["ctrl+shift+o"],
	"command": "reg_replace",
	"args": {"replacements": ["remove_deepl"]}
}
```

But unfortunately pressing that key-combination doesn't result in anything. I'm really not sure where I've gone wrong. I'm using:

- Sublime Text 3.0, Build 3170

**Comment by facelessuser** [comment]
I am not seeing this issue.  Check your console for errors.  Did you restart Sublime after installing?  Some times that is necessary.

I can't see your entire sublime-commands file, so I can't tell if you have something corrupted. In general, the commands should be in an top level array.  Right now, all I can assume is something is not right in your configuration files, but I see nothing wrong in the snippet you've posted.

**Comment by Jamahara** [comment]
Restarted Sublime Text several times after installing the package.

My console doesn't display any related issues either. 
```
DPI mode: per-monitor v2
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/home/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/home/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/home/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
top level value must be an array
pre session restore time: 0.29529
startup time: 0.36829
first paint time: 0.37129
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-regex
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin CSS Unminifier.CssUnminifier
reloading plugin jQueryDocs.jQueryDocs
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin RegReplace.rr_edit
reloading plugin RegReplace.rr_notify
reloading plugin RegReplace.rr_plugin
reloading plugin RegReplace.rr_replacer
reloading plugin RegReplace.rr_sequencer
reloading plugin RegReplace.rr_upgrade
reloading plugin RegReplace.support
reloading plugin SublimeLinter-jshint.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\home\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-jshint.sublime-package\linter.py", line 1, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin SublimeLinter-php.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\home\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-php.sublime-package\linter.py", line 14, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin Sublimerge 3.Sublimerge
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin SFTP.SFTP
reloading plugin SublimeHighlight.SublimeHighlight
reloading plugin tern_for_sublime.tern
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2018-05-18 19:16:30, next run at 2018-05-18 20:16:30 or after
```

This is the entire content of my **sublime-commands** file:
I removed the trailing comma just to see if that would change anything, but nothing.
```
{
    "caption": "Reg Replace: Remove DeepL",
    "command": "reg_replace",
    "args": { "replacements": ["remove_deepl"] }
}
```
At least I am now getting a few more entries in the command palette when typing "regreplace", still not showing my command though. 

![grafik](https://user-images.githubusercontent.com/25946865/40248866-922c4068-5ad1-11e8-96cf-44da6bba0322.png)
]

**Comment by facelessuser** [comment]
> This is the entire content of my sublime-commands file:

Then you are doing it wrong.  Each command should be in an array/list:

```js
[
    {
        "caption": "Reg Replace: Remove DeepL",
        "command": "reg_replace",
        "args": { "replacements": ["remove_deepl"] }
    }
]
```

**Comment by facelessuser** [comment]
Let me clarify **all** commands should be under **one** list.  Not a list for each command.

**Comment by Jamahara** [comment]
Thanks very much, it works perfectly fine now. 
I just followed the user guide and assumed it would be enough to copy and alter the parts shown in the description.
