### ISSUE TITLE
Getting an MdPopups failure to create popup when launching the Quick Start Guide in st3

### ISSUE THREAD

**Issue by sharun-s** [facelessuser/RegReplace#93]
Just installed RegReplace on SublimeText3 (3.2.2 build 3211) and tried running the Quick Start Guide. I get a MdPopups failed to create pop/phantom message. 

Console shows - 

```
mdpopups: Traceback (most recent call last):
  File "/home/s/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 664, in add_phantom
    nl2br=nl2br, allow_code_wrap=allow_code_wrap
  File "/home/s/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 328, in _create_html
    allow_code_wrap=allow_code_wrap
  File "/home/s/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 441, in md2html
    ).convert(_markup_template(markup, template_vars, template_env_options)).replace('&quot;', '"').replace('\n', '')
  File "/home/s/.config/sublime-text-3/Packages/python-markdown/st3/markdown/core.py", line 265, in convert
    self.lines = prep.run(self.lines)
  File "/home/s/.config/sublime-text-3/Packages/pymdownx/st3/pymdownx/superfences.py", line 737, in run
    return self.search_nested(lines)
  File "/home/s/.config/sublime-text-3/Packages/pymdownx/st3/pymdownx/superfences.py", line 601, in search_nested
    self.eval_fence(ws, content, start, end)
  File "/home/s/.config/sublime-text-3/Packages/pymdownx/st3/pymdownx/superfences.py", line 407, in eval_fence
    self.process_nested_block(ws, content, start, end)
  File "/home/s/.config/sublime-text-3/Packages/pymdownx/st3/pymdownx/superfences.py", line 451, in process_nested_block
    code = entry["formatter"](self.rebuild_block(self.code), self.lang, self.options, self.md)
  File "/home/s/.config/sublime-text-3/Packages/pymdownx/st3/pymdownx/superfences.py", line 666, in highlight
    linespecial=linespecial
  File "/home/s/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/highlight.py", line 450, in highlight
    code = highlight(src, lexer, formatter)
  File "/home/s/.config/sublime-text-3/Packages/pygments/all/pygments/__init__.py", line 87, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/home/s/.config/sublime-text-3/Packages/pygments/all/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/home/s/.config/sublime-text-3/Packages/pygments/all/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/home/s/.config/sublime-text-3/Packages/pygments/all/pygments/formatters/html.py", line 831, in format_unencoded
    source = self.wrap(source, outfile)
  File "/home/s/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/highlight.py", line 240, in wrap
    return self._wrap_code(self, source)
TypeError: _wrap_code() takes 2 positional arguments but 3 were given
```

- ST ver.: 3211
- Platform: linux
- Arch: x64
- Plugin ver.: 3.8.0
- Install via PC: True
- mdpopups ver.: 3.7.1
- backrefs ver.: 3.5
- regex ver.: 2.4.130
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

**Comment by facelessuser** [comment]
First time installs usually requires a restart of Sublime to load dependencies (like mdpopups) correctly the first time.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by sharun-s** [comment]
Ah I hardly ever close that window. 
Yup it works after restarting. Thanks! And another thanks for this very useful plugin! 🙏

**Comment by facelessuser** [comment]
You're welcome. Glad you got it working.
